title: Qile Wang's Homepage
page-top-title: Qile Wang
top-section-bg-text: Optical fiber sensing; Acoustic oceanography; Whale seismology
home-subtitle: Qile Wang&ensp;|&ensp;王其乐
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
